import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles/app.css';
import {scoreEssay} from './api.js';
import ScoreGauge from './components/ScoreGauge.jsx';
import DimensionCards from './components/DimensionCards.jsx';
import RadarChart from './charts/RadarChart.jsx';

const DEMO=`Education is one of the strongest tools available to individuals and communities because it develops knowledge, communication, and the ability to evaluate evidence. A strong education system should not only deliver information; it should help learners ask better questions, compare ideas, and explain their reasoning clearly.

However, access and quality are not equal in every context. Schools need qualified teachers, useful learning materials, supportive environments, and opportunities for students to practice what they learn. Technology can extend these opportunities when it is designed around genuine learning needs rather than novelty.

For these reasons, education should be treated as a long-term investment in human capability. Combining good teaching with thoughtful technology can make learning more accessible while preserving the importance of human guidance and judgment.`;

export default function App(){
 const [essay,setEssay]=useState(''); const [result,setResult]=useState(null); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 const stats=useMemo(()=>{const words=essay.trim()?essay.trim().split(/\s+/).length:0; const chars=essay.length; const sentences=essay.trim()?essay.split(/[.!?]+/).filter(Boolean).length:0; const paragraphs=essay.trim()?essay.split(/\n\s*\n/).filter(Boolean).length:0; return {words,chars,sentences,paragraphs}},[essay]);
 async function analyze(){setError('');setLoading(true);try{setResult(await scoreEssay(essay))}catch(e){setError(e.message)}finally{setLoading(false)}}
 return <main><header><div><span className="brand">ESSAYIQ</span><span className="eyebrow">AI WRITING ANALYTICS</span></div><div className="status"><span/> ONLINE</div></header><section className="hero"><p className="kicker">HYBRID NLP • REAL-TIME ANALYTICS</p><h1>Analyze Your Writing<br/><em>with AI.</em></h1><p>Paste an essay and receive an automated writing analytics report based on measurable text signals and a trained scoring model.</p></section><section className="editor panel"><div className="editor-head"><div><h2>Essay editor</h2><span className="muted">Your text is sent only when you select Analyze Essay.</span></div><button className="ghost" onClick={()=>setEssay(DEMO)}>Load demo essay</button></div><textarea value={essay} onChange={e=>setEssay(e.target.value)} placeholder="Paste your essay here..." aria-label="Essay text"/><div className="live-stats"><span>{stats.words} Words</span><span>{stats.sentences} Sentences</span><span>{stats.paragraphs} Paragraphs</span><span>{stats.chars} Characters</span></div><div className="actions"><button className="primary" disabled={loading||stats.words===0} onClick={analyze}>{loading?'Analyzing…':'Analyze Essay'}</button><button className="ghost" onClick={()=>{setEssay('');setResult(null);setError('')}}>Clear</button></div></section>{error&&<section className="error panel"><strong>ANALYSIS UNAVAILABLE</strong><p>{error}</p></section>}{result&&<section className="dashboard"><div className="score-row"><ScoreGauge score={result.score?.display}/><div className="model-panel panel"><p className="kicker">MODEL SIGNAL</p><h2>{result.model?.name}</h2><p>Version {result.model?.version} • {result.model?.trained?'trained model loaded':'training required'}</p><div className="interval"><span>Estimated range</span><strong>{result.uncertainty?.lower??'—'} — {result.uncertainty?.upper??'—'}</strong></div><small>This is an automated statistical estimate, not a replacement for qualified human assessment.</small></div></div><DimensionCards dimensions={result.dimensions}/><div className="grid"><section className="panel"><h2>Writing analytics</h2><RadarChart dimensions={result.dimensions}/></section><section className="panel"><h2>Writing statistics</h2><div className="stat-grid">{Object.entries(result.statistics||{}).map(([k,v])=><div className="stat" key={k}><span>{k.replaceAll('_',' ')}</span><strong>{v}{k==='lexical_diversity'?'%':''}</strong></div>)}</div></section></div><div className="grid"><section className="panel"><h2>Writing strengths</h2><ul className="feedback good">{(result.strengths||[]).map(x=><li key={x}>✓ {x}</li>)}</ul></section><section className="panel"><h2>Areas to review</h2><ul className="feedback">{(result.improvements||[]).map(x=><li key={x}>→ {x}</li>)}</ul></section></div></section>}<footer>EssayIQ • Educational analytics prototype • Analytical dimensions are derived indicators, not independently human-labeled scores.</footer></main>}

createRoot(document.getElementById('root')).render(<App/>);
